### ISSUE TITLE
data preparing 

### ISSUE THREAD

**Issue by WillQuCD** [mpc001/end-to-end-lipreading#2]
Thank you for your contribution!
Could you please give more details on data preparing?
Which model/code do you use to extract mouth ROI?
I can run this repository only after preparing the data by myself? right?

Thank you!

**Comment by mpc001** [comment]
Yes, we cannot provide the data since you need to download LRW first.
For video, we used the coordinates (x1, y1, x2, y2) = (80, 116, 175, 211) for cropping and then convert to grey images. For audio, we extract the wavfile with sampling rate 16K. The audio and video are both range from -1.0 to 1.0. These are what `def load_file(filename)` did.
